spring.datasource.url=jdbc:mysql://${LOCAL_MYSQL_HOST:127.0.0.1}:${LOCAL_MYSQL_PORT:13306}/${LOCAL_MYSQL_DATABASE:coffee_order}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${LOCAL_MYSQL_USERNAME:coffee}
spring.datasource.password=${LOCAL_MYSQL_PASSWORD:coffee}
spring.data.redis.host=${LOCAL_REDIS_HOST:127.0.0.1}
spring.data.redis.port=${LOCAL_REDIS_PORT:16379}
spring.kafka.bootstrap-servers=${LOCAL_KAFKA_BOOTSTRAP_SERVERS:127.0.0.1:19092}
