### Issue #10 인기 메뉴 Top 3 실제 HTTP 검증
GET {{baseUrl}}/api/menus/popular
Accept: application/json

### QA execution command
### curl.exe -sS -i http://localhost:8080/api/menus/popular

### QA observed response
### HTTP 200
### Content-Type: application/json
###
[]
